workflows:
    ios-hello-world:
      name: ios_hello_world
      environment:
        xcode: latest
        cocoapods: default
        flutter: stable
      triggering:
        events:
          - push
        branch_patterns:
          - pattern: 'wo_codesign'
            include: true
            source: true
      scripts:
        - xcodebuild --project "helloworld.xcodeproj" --scheme "helloworld" build
      artifacts:
        - build/ios/**/*.app
        - /tmp/xcodebuild_logs/*.log
