workflows:
    ios-hello-world:
      name: ios_hello_world
      environment:
        xcode: latest
        cocoapods: default
        flutter: stable
      triggering:
        events:
          - push
        branch_patterns:
          - pattern: 'wo_codesign'
            include: true
            source: true
      scripts:
        - xcodebuild -project "helloworld.xcodeproj" -scheme "helloworld" -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.4' clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      artifacts:
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
